#!/usr/bin/env bash

set +euH

source "${PWD}/engine.bash"

function usage {
    echo "./$(basename $0) -h --> shows usage"
}

CONTENTS=`list_contents ./contents`

show_list "${CONTENTS}"

SELECTED="`select_option "${CONTENTS}"`"

PREVIOUS=`in_contents_path "${SELECTED}"`

load_metadata $PREVIOUS

NEW_DATE=`change_date_from "${DATE}"`

NEW_FILENAME="`datefs "${NEW_DATE}"`-${SLUG_TITLE}"

create_content "${TITLE}" "${NEW_DATE}"

copy_content_from $PREVIOUS $NEW_FILENAME

rm -rf "./contents/${SELECTED}"
