#!/usr/bin/env bash

source "${PWD}/engine.bash"
source "${PWD}/template.bash"

MARKDOWN="comrak --unsafe "

function render_date_dest_fs {
    TZ=UTC date "+%Y/%m/%d" -d "${1}"
}

function render_content {
    source "${1}/metadata.sh"

    if [[ "${STATUS}" == "hidden" ]]; then
	log "skipping ${TITLE} `basename ${1}`"
	return;
    fi

    log "rendering ${TITLE} `basename ${1}`"

    local the_title=$TITLE
    local the_date=`render_date "${DATE}"`
    local the_content=`cat $PWD/contents/$FILENAME/content.md`
    local the_uri_date=`render_date_dest_fs "${DATE}"`
    local the_file_path="${3}/${the_uri_date}"
    local the_full_file_path="${the_file_path}/${SLUG}.html"
    local the_uri_path="${the_uri_date}/${SLUG}.html"

    mkdir -p $the_file_path

    local draft=""
    if [ "${STATUS}" != "" ]; then
	draft="<span>${STATUS}</span> &#10072;"
    fi

    render_html_wrapper $the_full_file_path "${the_uri_path}" "`cat <<-EOF | $MARKDOWN
# ${the_title}

<div class="content-info"><span>article</span> &#10072; ${draft} <time datetime="${DATE}">${the_date}</time></div>

${the_content}
EOF`"
}

function render_all_content {
    local ppath="${PWD}/contents"
    local contents="`ls ${ppath}`"

    for x in $contents; do
	render_content "$ppath/$x" "$x" "$1"
    done
}

function render_article_item {
    source "${1}/metadata.sh"

    if [[ "${STATUS}" == "hidden" ]]; then
	return;
    fi

    local the_title=$TITLE
    local the_date=`render_date "${DATE}"`
    local the_file_path="articles/`render_date_dest_fs "${DATE}"`"
    local the_url="${the_file_path}/${SLUG}.html"

    local draft=""
    if [ "${STATUS}" != "publish" ]; then
	draft="<span>${STATUS}</span> &#10072;"
    fi

    cat <<-EOF
<div class="article-item">
<a href="${the_url}"><h1>${the_title}</h1></a>
<div>${draft} <time class="content-datetime" datetime="${DATE}">${the_date}</time></div>
</div>
EOF
}

function render_index {
    DEST="${1}/index.html"

    local from="${PWD}/contents"
    local all_articles=""

    for x in `ls -r ${from}`; do
	all_articles="${all_articles}`render_article_item "${from}/${x}"`";
    done

    render_html_wrapper "${DEST}" "" "`cat <<-EOF | $MARKDOWN
${all_articles}
EOF`"
}
