#!/usr/bin/env bash

set +euH

source "${PWD}/engine.bash"

CONTENTS=`list_contents ./contents`

show_list "${CONTENTS}"

SELECTED="`select_option "${CONTENTS}"`"

load_metadata $SELECTED

make_content_metadata