#!/usr/bin/env bash

set +H

source "${ENGINE_PATH}/engine.bash"

function usage {
    echo "./$(basename $0) -h --> shows usage"
    echo "                 -w --> write to file"
    echo "                 -t --> content's title"
    echo "                 -d --> content's date"
}

expect_args "$*"

T=""
D=`now`

while getopts ":t:d:wph" arg; do
    case ${arg} in
	t) set_title "${OPTARG}"
	   ;;
	d) set_date "${OPTARG}"
	   ;;
	w) must_write
	   ;;
	h) usage
	   ;;
	?)
	echo "Invalid option: -${OPTARG}."
	exit 2
	;;
    esac
done

set_filename "`make_content_filepath`"
set_status "hidden"

is_dry_run && make_content_metadata || create_content "${TITLE}" "${DATE}"
