#!/usr/bin/env bash

set +H

source "${ENGINE_PATH}/engine.bash"

function usage {
    echo "./$(basename $0) -h --> shows usage"
    echo "                 -w --> write to file"
    echo "                 -t --> content's title"
    echo "                 -d --> content's date"
}

expect_args "$*"

T=""
D=`now`

while getopts ":t:d:wph" arg; do
    case ${arg} in
	t) T="${OPTARG}"
	   ;;
	d) D="${OPTARG}"
	   ;;
	w) must_write
	   ;;
	h) usage
	   ;;
	?)
	echo "Invalid option: -${OPTARG}."
	exit 2
	;;
    esac
done


is_dry_run && make_content_metadata || create_content "${T}" "${D}"
