#!/usr/bin/env bash

set -eu

source "${PWD}/tools.bash"

source "${PWD}/content-render"

DEST_DIR="${PWD}/../diasbruno.github.io/"

while getopts ":ph" arg; do
    case ${arg} in
	h)
	    usage
	   ;;
	?)
	echo "Invalid option: -${OPTARG}."
	exit 2
	;;
    esac
done

render_index $DEST_DIR
