#!/usr/bin/env bash

set -eu

source "${PWD}/tools.bash"

source "${PWD}/content-render"

DEST_DIR="${PWD}/../diasbruno.github.io/"

function usage {
    echo ""
    exit 1
}

while getopts ":ph" arg; do
    case ${arg} in
	h)
	    usage
	   ;;
	?)
	echo "Invalid option: -${OPTARG}."
	exit 2
	;;
    esac
done

log "rendering index"

render_index $DEST_DIR
