#!/usr/bin/env bash

set -eu

source "${PWD}/tools.bash"

PPATH=""

DEST_DIR="$PWD/../diasbruno.github.io/articles"

while getopts ":ph" arg; do
    case ${arg} in
	h)
	    usage
	   ;;
	f)
	    PPATH="${OPTARG}"
	    ;;
	?)
	echo "Invalid option: -${OPTARG}."
	exit 2
	;;
    esac
done

source "${PWD}/content-render"

render_all_content $DEST_DIR
