#!/usr/bin/env bash

set +euH

source "${PWD}/engine.bash"

NEW_STATUS="draft"

function usage {
    echo "./$(basename $0) -h --> shows usage"
    echo "                 -p --> publish"
    echo "                 -d --> draft"
    echo "                 -n --> hidden"
    echo "                 -w --> write to file"
    exit 1
}

function update_metadata {
    write_content_metadata $FILENAME
    log "wrote ${FILENAME}"
}

expect_args "$*"

while getopts ":dwphn" arg; do
    case ${arg} in
	d)
	    NEW_STATUS="draft"
	    ;;
	p)
	    NEW_STATUS="publish"
	    ;;
	n)
	    NEW_STATUS="hidden"
	    ;;
	w)
	    must_write
	    ;;
	h)
	    usage
	    ;;
	?)
	echo "Invalid option: -${OPTARG}."
	exit 2
	;;
    esac
done

CONTENTS=`list_contents ./contents`

show_list "${CONTENTS}"

SELECTED="`select_option "${CONTENTS}"`"

load_metadata $SELECTED

set_status "${NEW_STATUS}"

is_dry_run && make_content_metadata || update_metadata
