name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: dependencies
      run: |
        sudo apt install libunac1-dev
        sudo git clone http://github.com/diasbruno/slugifier.git /usr/src/slugifier
        cd /usr/src/slugifier
        sudo make
        sudo DEST=/usr/bin make install

    - name: tests
      run: make -C ./t
